VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_PATCH = 0


DEFINES += DEPLOYMENT_PATH=\"\\\"\"/usr/share/harbour-vodman/\"\\\"\"
DEFINES += VODMAN_APP_NAME=\"\\\"\"harbour-vodman/\"\\\"\"
DEFINES += VODMAN_VERSION_MAJOR=$$VERSION_MAJOR
DEFINES += VODMAN_VERSION_MINOR=$$VERSION_MINOR
DEFINES += VODMAN_VERSION_PATCH=$$VERSION_PATCH


INCLUDEPATH += $$PWD/src/vodman-lib

